
services:
  benji-api-v1:
    container_name: benji-api-v1
    image: daniloarantesf/benjaminfenix_api
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - "3016:3016"
    restart: always

  #client:
  #  container_name: client
  #  image: daniloarantesf/benjaminfenix_client
  #  build:
  #    dockerfile: Dockerfile
  #    context: "./benji-client"
  #  ports:
  #    - "3010:3010"
  #  links:
  #    - api
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
